Course project
pepelulka/OS_labs pull request #5
Opened 2023-12-25 03:07 UTC by pepelulka

2023-12-25 20:57 UTC, QElderDelta requested changes

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +    static TMapStringToStrings inverse(TMapStringToStrings &map) {
А чего не в .cpp?

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +    TJobDag(const std::vector<TJob>& jobs,
Тоже в .cpp

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +    void print() {
И это в .cpp

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +            *this = temp;
Стремно выглядит. Почему бы не класть сразу в себя, а потом передать в CheckCorrectness *this

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +    static bool CheckCorectness(TJobDag &dag);
CheckCorrectness

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_dag.hpp
> +    static TMapStringToStrings inverse(TMapStringToStrings &map) {
Какие-то функции с маленькой, какие-то с большой. Сделай все по кодстайлу

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_exec.hpp
> +    static int Exec(const std::string& path) {
В .cpp

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_exec.hpp
> +        l.unlock();
Самому писать unlock руками - зашквар, лучше так:
```cpp
void push(const std::string &str) {
  {
    std::unique_lock l(mut);
    completed.push_back(str);
  }
  cv.notify_one();
}
```

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_exec.hpp
> +    const static size_t STANDART_MAX_PROC_COUNT = 4;
constexpr

2023-12-25 20:57 UTC, QElderDelta commented on cp/include/job_exec.hpp
> +    // std::mutex cMut;
Убрать закомменченный код

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +    for (auto p : dag.jobs) {
const auto&

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +    for (auto p : dag.dep) {
const auto&

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +        for (auto i : p.second) {
const auto&

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +    for (auto p : dep) {
const auto&

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +    for (auto p : dep) {
const auto&

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +        auto job = p.second;
А копии тебе-то зачем? const auto& опять же

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_dag.cpp
> +        for (auto dep : jsn["dependencies"]) {
Последний раз пишу про const auto& - дальше сам везде поправишь

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +    lk1.unlock();
Аналогичное замечание про unlock

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +bool TDagJobExecutor::Execute(TJobDag &dag) {
А почему не const TJobDag& dag

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +    std::set<std::string> executionQueue;
Можно сэкономить память и класть сюда std::string_view

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +    std::map<std::string, int> countOfDeps;
То же самое - std::string_view

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +        // std::unique_lock l1(cMut);
Убрать закомменченный код

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +                    mutexState[mtx] = false;
Доступ к mutexState без мьютекса, можно дата рейс поймать

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +                    mutexState[mtx] = false;
Я думаю лучше в mutexState std::atomic<bool> чтобы лежал

2023-12-25 20:57 UTC, QElderDelta commented on tests/cp_test.cpp
> +    cp::TDagJobExecutor ex(4);
С несколькими потоками быстрее получается, чем с одним?

2023-12-25 20:57 UTC, QElderDelta commented on tests/cp_test.cpp
> +TEST(CP, Test3) {
Это уже не совсем юнит тесты, скорее end-to-end. Юниты можно было бы написать, например, на парсер json'а(только лучше json захардкодить в код тестов, чем отдельным файликом держать) или на checkCorrectness

2023-12-25 20:57 UTC, QElderDelta commented on tests/cp_test.cpp
> +TEST(CP, Test3) {
Но пойдет

2023-12-25 20:57 UTC, QElderDelta commented on cp/src/job_exec.cpp
> +        exit(EXIT_FAILURE);
Исключение из Exec тогда тоже лучше поймать и сделать exit

2023-12-26 06:47 UTC, pepelulka commented on tests/cp_test.cpp
> +    cp::TDagJobExecutor ex(4);
Так точно

2023-12-28 21:01 UTC, merged